openapi: 3.0.0
info:
  version: '0.0.2'
  title: Blog
  license:
    name: Apache 2.0
  description: 'Blog Service APIs'
  contact:
    name: Kong-dev
servers:
  - url: ${dev_portal_sample_baseurl}
    description: Sample Serverless Gateway for Dev Portal
  - url: 'http://httpbin.org/anything'
paths:
  '/blogs':
    post:
      operationId: addBlog
      summary: Add a blog
      description: This API adds a blog
      responses:
        '200':
          description: Add a Blog
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  addBlog:
                    blog_id: '2'
                    text: this is my second happy blog
                    sentiment_score: 0.5
                    created_on: '2024-08-01T00:00:00.000Z'
                extensions:
                  tracing:
                    version: 1
                    startTime: '2024-08-01T12:52:15.877Z'
                    endTime: '2024-08-01T12:52:15.893Z'
                    duration: 15290050
                    execution:
                      resolvers:
                      - path:
                        - addBlog
                        parentType: Mutation
                        fieldName: addBlog
                        returnType: Blog
                        startOffset: 349573
                        duration: 14728099
                      - path:
                        - addBlog
                        - blog_id
                        parentType: Blog
                        fieldName: blog_id
                        returnType: ID!
                        startOffset: 15141465
                        duration: 35624
                      - path:
                        - addBlog
                        - text
                        parentType: Blog
                        fieldName: text
                        returnType: String
                        startOffset: 15194268
                        duration: 19521
                      - path:
                        - addBlog
                        - sentiment_score
                        parentType: Blog
                        fieldName: sentiment_score
                        returnType: Float
                        startOffset: 15222495
                        duration: 13283
                      - path:
                        - addBlog
                        - created_on
                        parentType: Blog
                        fieldName: created_on
                        returnType: String
                        startOffset: 15243878
                        duration: 9111
    get:
      operationId: getBlogs
      summary: Get blogs
      description: This API gets all blogs
      responses:
        '200':
          description: Blog
          content:
            application/json:
              schema:
                type: object
              example:
                data:
                  getBlogs:
                  - blog_id: '1'
                    text: hello blog, I'm a blog one. this is my content, and I'm content.
                    sentiment_score: 0
                    created_on: '2024-08-01T00:00:00.000Z'
                  - blog_id: '2'
                    text: hello blog, I'm a blog two, how about you?
                    sentiment_score: 0
                    created_on: '2024-08-01T00:00:00.000Z'
                  - blog_id: '3'
                    text: hello blog, I'm blog three, what'll it be?
                    sentiment_score: 0
                    created_on: '2024-08-01T00:00:00.000Z'
                extensions:
                  tracing:
                    version: 1
                    startTime: '2024-08-01T12:52:19.052Z'
                    endTime: '2024-08-01T12:52:19.063Z'
                    duration: 10776451
                    execution:
                      resolvers:
                      - path:
                        - getBlogs
                        parentType: Query
                        fieldName: getBlogs
                        returnType: "[Blog]"
                        startOffset: 1676085
                        duration: 7921700
                      - path:
                        - getBlogs
                        - 0
                        - blog_id
                        parentType: Blog
                        fieldName: blog_id
                        returnType: ID!
                        startOffset: 9669008
                        duration: 35346
                      - path:
                        - getBlogs
                        - 0
                        - text
                        parentType: Blog
                        fieldName: text
                        returnType: String
                        startOffset: 9719346
                        duration: 15921
                      - path:
                        - getBlogs
                        - 0
                        - sentiment_score
                        parentType: Blog
                        fieldName: sentiment_score
                        returnType: Float
                        startOffset: 9743914
                        duration: 12845
    options:
      summary: CORS support for the blog endpoint
      description: Handles CORS preflight requests for /blogs.
      responses:
        '204':
          description: No Content. CORS preflight response.
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: 'GET, POST, OPTIONS'
  '/blogs/{id}':
    get:
      operationId: getBlogById
      summary: Get a blog by id
      description: This API gets a blog by ID
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "ID of blog to use",
          "required": true,
          "schema": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "style": "simple"
        }
      ]
      responses:
        '200':
          description: Blog
      tags:
      - blog
tags:
- name: blog
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey